### ISSUE TITLE
high cpu usage in handshake

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p-secio#42]
was poking around on mars (one of the default bootstrappers) and noticed that the thing using the most cpu time was RSA signing in secio.

Heres a listing of the method: https://gist.github.com/whyrusleeping/513cf154eb9c392668e088843b2f6b00

My thoughts are that this is probably a wontfix, mars is likely just getting so many incoming connections, and RSA signing is actually mildly expensive, so the combination of the two is just expensive. I can see this getting better if we switched mars to use an ed25519 key, or switched to TLS1.3.

Maybe theres something unnecessarily expensive here that we can optimize in the mean time though?

**Comment by raulk** [comment]
We can get a reasonable kick from switching to openssl via [spacemonkeygo/openssl](https://godoc.org/github.com/spacemonkeygo/openssl) (Cgo bindings for openssl). Rather than forcing openssl, we can find a way to compile with/without support with build flags, depending on the target machine?

```
❯ go test -bench=.*BenchmarkRSA.*
goos: darwin
goarch: amd64
pkg: github.com/libp2p/go-libp2p-crypto
BenchmarkRSAOpenSSL-8   	   20000	     98060 ns/op
BenchmarkRSAStdlib-8    	    5000	    345898 ns/op
PASS
ok  	github.com/libp2p/go-libp2p-crypto	4.919s
```

We can also plan a migration to Ed25519 keys on mars. Challenge here will be rolling out the upgrade and preserving backwards compatibility.

---
Benchmark: https://gist.github.com/raulk/f86bd1a3061c9319c0cd1bbc980a320d

**Comment by whyrusleeping** [comment]
@raulk adding support based on build flags should be pretty easy to do. Mars is now currently maxed out on CPU usage entirely from RSA nonsense.
